export const SIGN_NAME = '张艳华的博客';
export const TEMPLATE_CODE = 'SMS_461795767';
export const ACCESS_KEY = 'ALIBABA_CLOUD_ACCESS_KEY_ID';
export const ALIBABA_CLOUD_ACCESS_KEY_SECRET =
  'ALIBABA_CLOUD_ACCESS_KEY_SECRET';
